### ISSUE TITLE
apt does not exist Under Java 1.8 and higher

### ISSUE THREAD

**Issue by stuaxo** [OpenEndedGroup/Field#58]
Trying to build with ant under Ubuntu 14.10 (Utopic)

```
Buildfile: /mnt/data/home/stu/projects/external/Field/Contents/build.xml

build_apt:
    [mkdir] Created dir: /mnt/data/home/stu/projects/external/Field/Contents/core/.apt_generated

BUILD FAILED
/mnt/data/home/stu/projects/external/Field/Contents/build.xml:27: apt does not exist under Java 1.8 and higher

Total time: 0 seconds
```

**Comment by marcdownie** [comment]
It's true: Field needs a 1.7 JDK to build (but runs fine on 1.8).

**Comment by stuaxo** [comment]
Realised that because I on Ubuntu I can use the update-altrnatives to temporarily choose a version 7 JDK  http://stackoverflow.com/questions/21115133/ubuntu-change-the-path-from-openjdk-6-to-oracle-jdk-7  then switch back to 8 when done building.

Cheers for the info, looks like an annoying API change, I hadn't heard of the deprecated API or JSR 269 that replaces until yesterday.

Got it running, now - there seem to be quite a lot of exceptions appearing in the terminal - mostly like this:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at field.bytecode.protect.DeferedNextUpdate$1.update(DeferedNextUpdate.java:47)
	at field.launch.Launcher$4.run(Launcher.java:328)
	at org.eclipse.swt.widgets.Display.timerProc(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at field.launch.Launcher.main(Launcher.java:93)
Caused by: java.lang.NullPointerException
	at field.core.plugins.help.HelpBrowser.isPinned(HelpBrowser.java:500)
	at field.core.plugins.help.ContextualHelp.offerHelp_original(ContextualHelp.java:160)
	... 11 more

```

**Comment by stuaxo** [comment]
Sorry for polluting this ticket:

Looks like things aren't quite working - I added a visual element, but it doesn't appear to be there -

http://imgur.com/RviOsJ8

I'm new to Field, but get the idea there

**Comment by marcdownie** [comment]
Well, something's definitely busted, but we'll actually need those exceptions in the terminal to make progress on this. Put them all in a gist (https://gist.github.com/)?

**Comment by stuaxo** [comment]
OK, here is running in openjdk7 with the different script variations:

Thee ones fail:
```
./field_linux64_8_noreload.sh 
/home/stu/projects/external/Field/Contents/linux/..
rm: cannot remove ‘../core/classes/org/eclipse/swt’: No such file or directory
./field_linux64_8_noreload.sh: line 7: /usr/lib/jvm/jdk1.8.0/bin/java: No such file or directory
```

```
./field_linux64_8.sh 
/home/stu/projects/external/Field/Contents/linux/..
rm: cannot remove ‘../core/classes/org/eclipse/swt’: No such file or directory
./field_linux64_8.sh: line 7: /usr/lib/jvm/jdk1.8.0/bin/java: No such file or directory
```

This one displays a window before dying:
```
./field_linux64_nr.sh 
/home/stu/projects/external/Field/Contents/linux/..
rm: cannot remove ‘../core/classes/org/eclipse/swt’: No such file or directory
 hello 
## trampoline <class field.bytecode.protect.StandardTrampoline:sun.misc.Launcher$AppClassLoader@40f186b8>
 warning: wildcard path </home/marc/fieldwork/personal/classpath/**> is not a directory or does not exist 
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/syphon/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/syphon.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/gstreamer/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/gstreamer.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/wrap/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/wrap.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/online/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/online.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/reload/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/reload.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../lib/jruby-complete-1.6.7.jar>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/languages.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/osc/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/osc.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/typing/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/typing.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/scrubber/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/scrubber.mf doesn't exist
 warning, path </home/marc/fieldwork/personal/classes>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/personal.mf doesn't exist
 platform is :linux / Linux  false
 -- registering open document handler --
 -- registering open document handler complete --
--- into workspace directory, in search of bug #142:
   versioning dir is set to </mnt/data/home/stu/Documents/FieldWorkspace/FieldWorkspace> which exists? <true>
 user home is </home/stu>
 and we're out of workspacedirectory(), still looking for #142: dir is </mnt/data/home/stu/Documents/FieldWorkspace/FieldWorkspace> and new <true>
 platform is :linux / Linux  false
 sheets are :[]
 find library <jawt>
 find library <lwjgl64>
 find library <lwjgl>
WARNING: skipping cache, classpath is not final or correct <-5340551144223682984 4596563103849563952>. This is completely benign, but starting Field might take longer than usual.
java.lang.Terminator$1@2a3c779d
 --- importing module from extensions directory <mmodule>
 --- executing file from extensions directory </home/stu/projects/external/Field/Contents/linux/../extensions>
hello Field
 font :Font {139693784395792}
 about to open tools 
 about to open tools finished 
 about to open tools 
 about to open tools finished 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0cb4649451, pid=22704, tid=139693873317632
#
# JRE version: OpenJDK Runtime Environment (7.0_75-b13) (build 1.7.0_75-b13)
# Java VM: OpenJDK 64-Bit Server VM (24.75-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.5.4
# Distribution: Ubuntu 14.10, package 7u75-2.5.4-1~utopic1
# Problematic frame:
# C  [libsoup-2.4.so.1+0x6f451]  soup_session_feature_detach+0x11
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/data/home/stu/projects/external/Field/Contents/Resources/hs_err_pid22704.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./field_linux64_nr.sh: line 7: 22704 Aborted                 java -noverify -Xmx4g -Dcom.sun.media.jai.disableMediaLib=true -Dorg.lwjgl.util.NoChecks=false -Dorg.eclipse.swt.browser.UseWebKitGTK=True -Dorg.eclipse.swt.browser.DefaultType=webkit -Dsun.java2d.opengl=false -Djava.library.path=$fieldhome/lib/linux64/:$fieldhome/Java/ -Dpython.path=$fieldhome/lib/python/:$fieldhome/python/ -classpath $fieldhome/lib/jna-3.2.4.jar:$fieldhome/core/classes/:$fieldhome/Resources/:$fieldhome/lib/:$fieldhome/lib/linux64/swt.jar:$fieldhome/lib/linux64/lwjgl.jar:$fieldhome/lib/linux64/lwjgl_util.jar:/usr/lib/jvm/java-6-openjdk/lib/tools.jar:$fieldhome/lib/jai_codec.jar:$fieldhome/lib/jai_core.jar:$fieldhome/lib/asm-all-3.2.jar:$fieldhome/lib/itext-2.0.6.jar:$fieldhome/lib/jython-complete.jar:$fieldhome/lib/parboiled4j-snapshot.jar:$fieldhome/lib/pegdown-0.8.5.4.jar:$fieldhome/lib/qdox-2.0-20100906.201255-1.jar:$fieldhome/lib/writeMethodAPT.jar:$fieldhome/lib/xpp3-1.1.3.4d_b4_min.jar:$fieldhome/lib/xstream-SNAPSHOT.jar:$fieldhome/Java/:$fieldhome/lib/batik-all.jar:$fieldhome/extras/bin/gstreamer/gstreamer-java.jar:$fieldhome/extras/bin/gstreamer/jna.jar:$fieldhome/extras/bin/gstreamer/:$fieldhome/lib/jruby-complete-1.6.7.2.jar:/usr/lib/jvm/jdk1.7.0/lib/tools.jar -Dtrampoline.class=field.bytecode.protect.StandardTrampoline -Dpython.security.respectJavaAccessibility=false -Dmain.class=field.Blank2 field.launch.Launcher -extensions.dir $fieldhome/extensions/ ${*}
```

...Here is the gist for the linux64_mozilla.sh which does kind of work to a point:
https://gist.github.com/stuaxo/5e1b5aa8757b5c8f7623

Ok, so SyphonPlugin breaks - kind of understandable, since no syphon on linux, I also don't have Max... some of these other ones probably should work though.

**Comment by stuaxo** [comment]
For completeness here is the oracle 8 scripts output (after I update-alternatives to oracle java 8)

```
/field_linux64_oracle8.sh 
/home/stu/projects/external/Field/Contents/linux/..
rm: cannot remove ‘../core/classes/org/eclipse/swt’: No such file or directory
 hello 
0.175: Total time for which application threads were stopped: 0.0000869 seconds
0.185: Total time for which application threads were stopped: 0.0000740 seconds
## trampoline <class field.bytecode.protect.StandardTrampoline:sun.misc.Launcher$AppClassLoader@2a139a55>
0.238: Total time for which application threads were stopped: 0.0001233 seconds
 warning: wildcard path </home/marc/fieldwork/personal/classpath/**> is not a directory or does not exist 
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/syphon/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/syphon.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/gstreamer/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/gstreamer.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/wrap/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/wrap.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/online/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/online.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/reload/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/reload.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../lib/jruby-complete-1.6.7.jar>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/languages.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/osc/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/osc.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/typing/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/typing.mf doesn't exist
 warning, path </home/stu/projects/external/Field/Contents/linux/../extensions/../extras/scrubber/bin>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/scrubber.mf doesn't exist
 warning, path </home/marc/fieldwork/personal/classes>added to classpath through Field-RedirectionPath inside extension /home/stu/projects/external/Field/Contents/linux/../extensions/personal.mf doesn't exist
 platform is :linux / Linux  false
 -- registering open document handler --
 -- registering open document handler complete --
0.298: Total time for which application threads were stopped: 0.0001397 seconds
0.383: Total time for which application threads were stopped: 0.0001673 seconds
0.384: Total time for which application threads were stopped: 0.0001130 seconds
0.429: Total time for which application threads were stopped: 0.0003492 seconds
--- into workspace directory, in search of bug #142:
   versioning dir is set to </mnt/data/home/stu/Documents/FieldWorkspace/FieldWorkspace> which exists? <true>
 user home is </home/stu>
 and we're out of workspacedirectory(), still looking for #142: dir is </mnt/data/home/stu/Documents/FieldWorkspace/FieldWorkspace> and new <true>
 platform is :linux / Linux  false
 sheets are :[]
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
0.593: Total time for which application threads were stopped: 0.0002401 seconds
 -- skipping interface description for <java/lang/CharSequence>
 -- skipping interface description for <java/lang/CharSequence>
 -- skipping interface description for <java/lang/CharSequence>
0.661: Total time for which application threads were stopped: 0.0002894 seconds
0.896: Total time for which application threads were stopped: 0.0004600 seconds
0.910: Total time for which application threads were stopped: 0.0003610 seconds
 find library <jawt>
 find library <lwjgl64>
 find library <lwjgl>
1.096: Total time for which application threads were stopped: 0.0001688 seconds
1.120: Total time for which application threads were stopped: 0.0003488 seconds
1.121: Total time for which application threads were stopped: 0.0002980 seconds
1.124: Total time for which application threads were stopped: 0.0001867 seconds
2.036: Total time for which application threads were stopped: 0.0007727 seconds
2.156: Total time for which application threads were stopped: 0.0005116 seconds
2.692: Total time for which application threads were stopped: 0.0002371 seconds
2.837: Total time for which application threads were stopped: 0.0004350 seconds
2.849: Total time for which application threads were stopped: 0.0004304 seconds
2.850: Total time for which application threads were stopped: 0.0003663 seconds
2.978: Total time for which application threads were stopped: 0.0001970 seconds
3.065: [Full GC (Metadata GC Threshold)  134M->18M(4096M), 0.1652333 secs]
3.231: Total time for which application threads were stopped: 0.1655550 seconds
3.283: Total time for which application threads were stopped: 0.0004889 seconds
3.377: Total time for which application threads were stopped: 0.0004834 seconds
3.691: Total time for which application threads were stopped: 0.0008128 seconds
3.697: Total time for which application threads were stopped: 0.0004284 seconds
3.698: Total time for which application threads were stopped: 0.0002732 seconds
3.737: Total time for which application threads were stopped: 0.0002941 seconds
3.881: Total time for which application threads were stopped: 0.0002349 seconds
3.933: Total time for which application threads were stopped: 0.0001751 seconds
 -- skipping interface description for <java/lang/CharSequence>
 -- skipping interface description for <java/lang/CharSequence>
4.177: Total time for which application threads were stopped: 0.0001453 seconds
4.177: Total time for which application threads were stopped: 0.0000602 seconds
4.177: Total time for which application threads were stopped: 0.0001026 seconds
4.178: Total time for which application threads were stopped: 0.0000873 seconds
4.179: Total time for which application threads were stopped: 0.0000645 seconds
4.179: Total time for which application threads were stopped: 0.0000957 seconds
4.180: Total time for which application threads were stopped: 0.0000962 seconds
4.243: Total time for which application threads were stopped: 0.0000803 seconds
4.243: Total time for which application threads were stopped: 0.0000323 seconds
4.243: Total time for which application threads were stopped: 0.0000320 seconds
4.252: Total time for which application threads were stopped: 0.0005331 seconds
4.355: Total time for which application threads were stopped: 0.0001522 seconds
4.395: Total time for which application threads were stopped: 0.0001210 seconds
4.395: Total time for which application threads were stopped: 0.0000563 seconds
4.395: Total time for which application threads were stopped: 0.0000519 seconds
4.417: Total time for which application threads were stopped: 0.0004210 seconds
4.431: Total time for which application threads were stopped: 0.0009805 seconds
4.444: Total time for which application threads were stopped: 0.0003919 seconds
4.445: Total time for which application threads were stopped: 0.0003136 seconds
4.579: Total time for which application threads were stopped: 0.0005859 seconds
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/reflect/AnnotatedElement>
 -- skipping interface description for <java/lang/CharSequence>
 -- skipping interface description for <java/lang/CharSequence>
4.691: Total time for which application threads were stopped: 0.0001327 seconds
java.lang.Terminator$1@67cefd84
4.704: [Full GC (Metadata GC Threshold)  180M->29M(4096M), 0.1232240 secs]
4.828: Total time for which application threads were stopped: 0.1233691 seconds
 --- importing module from extensions directory <mmodule>
 --- executing file from extensions directory </home/stu/projects/external/Field/Contents/linux/../extensions>
hello Field
 -- skipping interface description for <java/lang/CharSequence>
 -- skipping interface description for <java/lang/CharSequence>
 font :Font {140143523939200}
 about to open tools 
 about to open tools finished 
5.084: Total time for which application threads were stopped: 0.0006037 seconds
5.261: Total time for which application threads were stopped: 0.0001264 seconds
5.261: Total time for which application threads were stopped: 0.0000542 seconds
 about to open tools 
 about to open tools finished 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f74de8b9451, pid=23088, tid=140143651747584
#
# JRE version: Java(TM) SE Runtime Environment (8.0_25-b17) (build 1.8.0_25-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libsoup-2.4.so.1+0x6f451]  soup_session_feature_detach+0x11
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/data/home/stu/projects/external/Field/Contents/Resources/hs_err_pid23088.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./field_linux64_oracle8.sh: line 9: 23088 Aborted                 $JRE/jre/bin/java -noverify -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:+UseG1GC -XX:MaxGCPauseMillis=40 -XX:GCPauseIntervalMillis=100 -XX:+PrintGC -Xmx4g -Xms4g -Dcom.sun.media.jai.disableMediaLib=true -Dorg.lwjgl.util.NoChecks=false -Dorg.eclipse.swt.browser.UseWebKitGTK=True -Dorg.eclipse.swt.browser.DefaultType=webkit -Dsun.java2d.opengl=false -Djava.library.path=$fieldhome/lib/linux64/:$fieldhome/Java/ -Dpython.path=$fieldhome/lib/python/:$fieldhome/python/ -classpath $fieldhome/lib/jna-3.2.4.jar:$fieldhome/core/classes/:$fieldhome/Resources/:$fieldhome/lib/:$fieldhome/lib/linux64/swt.jar:$fieldhome/lib/linux64/lwjgl.jar:$fieldhome/lib/linux64/lwjgl_util.jar:$JRE/lib/tools.jar:$fieldhome/lib/jai_codec.jar:$fieldhome/lib/jai_core.jar:$fieldhome/lib/asm-all-3.2.jar:$fieldhome/lib/itext-2.0.6.jar:$fieldhome/lib/jython-complete.jar:$fieldhome/lib/parboiled4j-snapshot.jar:$fieldhome/lib/pegdown-0.8.5.4.jar:$fieldhome/lib/qdox-2.0-20100906.201255-1.jar:$fieldhome/lib/writeMethodAPT.jar:$fieldhome/lib/xpp3-1.1.3.4d_b4_min.jar:$fieldhome/lib/xstream-SNAPSHOT.jar:$fieldhome/Java/:$fieldhome/lib/batik-all.jar:$fieldhome/extras/bin/gstreamer/gstreamer-java.jar:$fieldhome/extras/bin/gstreamer/jna.jar:$fieldhome/extras/bin/gstreamer/:$fieldhome/lib/jruby-complete-1.6.7.2.jar -Dtrampoline.class=field.bytecode.protect.StandardTrampoline -Dpython.security.respectJavaAccessibility=false -Dmain.class=field.Blank2 field.launch.Launcher -extensions.dir $fieldhome/extensions/ ${*}

```

**Comment by bluecamel** [comment]
Is there a build available that works on OS X 10.10?  It's not exactly easy to get Java 7 going along with Java 8.
